apiVersion: v1
kind: Service
metadata:
  name: corecrud-mongodb-service
spec:
  selector:
    app: corecrud-mongodb
  ports:
  - protocol: TCP
    port: 27017
    
---

apiVersion: v1
kind: Service
metadata:
  name: corecrud-service
spec:
  selector:
    app: corecrud
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer