apiVersion: apps/v1
kind: Deployment
metadata:
  name: corecrud
spec:
  replicas: 3
  selector:
    matchlabels:
      app: corecrud
  template:
    metadata:
      labels:
        app: corecrud
    spec:
      containers:
      - name: corecrud-container
        image: fabricioveronez/corecrud:v2
        ports:  
        - containerPort: 80
        env:
        - name: MONGO_CONNECTIONSTRING
          value: "mongodb://teste:123456@corecrud"
        - name: MONGO_DATABASE
          value: "admin"